name: Update prebuilt blobs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - module: "Samsung China apps"
            path: "unica/packages/china"
          - module: "(Exynos) Optical FOD blobs"
            path: "unica/packages/fod/essi"
          - module: "(Qualcomm) Optical FOD blobs"
            path: "unica/packages/fod/qssi"
          - module: "(Exynos) Knox'nt blobs"
            path: "unica/packages/knox/essi/none"
          - module: "(Exynos) Knox SDP blobs"
            path: "unica/packages/knox/essi/sdp"
          - module: "(Qualcomm) Knox DDAR/SDP blobs"
            path: "unica/packages/knox/qssi/ddar_sdp"
          - module: "(Qualcomm) Knox'nt blobs"
            path: "unica/packages/knox/qssi/none"
          - module: "(Qualcomm) Knox SDP blobs"
            path: "unica/packages/knox/qssi/sdp"
          - module: "Low-end Samsung Camera app"
            path: "unica/packages/mass_cam"
          - module: "VNDK 30 apex"
            path: "unica/packages/vndk/30"
          - module: "VNDK 31 apex"
            path: "unica/packages/vndk/31"
          - module: "VNDK 32 apex"
            path: "unica/packages/vndk/32"
          - module: "VNDK 33 apex"
            path: "unica/packages/vndk/33"
          - module: "(r8q) OS proprietary blobs"
            path: "target/r8q/patches/stock_blobs"
          - module: "(r8q) /vendor proprietary blobs"
            path: "target/r8q/patches/vendor"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Free disk space
        uses: rokibhasansagar/slimhub_actions@main
        with:
          retain: 'compiler_cmake'

      - name: Set up build environment
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            attr ccache clang golang libbrotli-dev \
            libgtest-dev libprotobuf-dev libunwind-dev libusb-1.0-0-dev libzstd-dev \
            linux-modules-extra-$(uname -r) lld ninja-build protobuf-compiler zipalign signapk
          sudo modprobe erofs f2fs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Build dependencies
        run: source ./buildenv.sh a52sxq

      - name: Update prebuilt blobs
        run: |
          source ./buildenv.sh a52sxq
          ./scripts/internal/update_prebuilt_blobs.sh ${{ matrix.path }}
          echo "PDA_BUILD=$(cat ./${{ matrix.path }}/.current | cut -d "/" -f 1)" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            ${{ matrix.path }}
          commit-message: '${{ matrix.path }}: update blobs to ${{ env.PDA_BUILD }}'
          committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          branch: '${{ matrix.path }}'
          delete-branch: true
          title: 'Update ${{ matrix.path }} blobs to ${{ env.PDA_BUILD }}'
          body: ''
